import Head from 'next/head';
import { useState, useEffect } from 'react';
import WeatherView from 'components/WeatherView/WeatherView';
import { PulseLoader } from 'react-spinners';
import SearchForm from '../../components/SearchForm';
import Overlay from '../../components/Overlay';
import Background from '../../components/Background';
import fetchWeather from './api/fetchWeather';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// const API_KEY = '61660147351f6b748481fd295b55cbb1';

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!city) {
      return;
    }
    setIsLoading(true);

    // const weatherAPI = () => {
    //   axios
    //     .get(
    //       `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_API_KEY}`
    //     )
    //     .then((response) => {
    //       setWeather(response.data);
    //     })
    //     .catch((error) => {
    //       setError(error);
    //       toast.error('The city was not found. Please try again');
    //     })
    //     .finally(() => {
    //       setIsLoading(false);
    //       setError(null);
    //     });
    // };

    fetchWeather(city)
      .then((res) => {
        setWeather(res.data);
      })
      .catch((err) => {
        setError(err);
        toast.error('The city was not found. Please try again');
      })
      .finally(() => {
        setIsLoading(false);
        setError(null);
      });
    // weatherAPI();
  }, [city]);

  const onSubmit = (e) => {
    e.preventDefault();
    if (!e.target.elements.searchForm.value) {
      return toast.warning('Please enter a city name');
    }
    setCity(e.target.elements.searchForm.value.trim().toLowerCase());
    setWeather({});
    e.target.elements.searchForm.value = '';
  };

  return (
    <div className="h-screen">
      <Head>
        <title>Weather App on NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* overlay */}

      <Overlay />
      {/* <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" /> */}

      {/* bg-image */}

      <Background />
      {/* <Image
        src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/8/2022/10/CLI371.weather.double_rainbow_cammie_czuchnicki-920x614.jpg"
        alt="/"
        layout="fill"
        className="object-cover"
      /> */}

      {/* search form */}

      <SearchForm onSubmitAction={onSubmit} />

      <ToastContainer
        position="top-right"
        autoClose={2000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="dark"
      />

      {/* weather data display */}

      {isLoading && (
        <div className="flex justify-center items-center mt-16">
          <PulseLoader color="#fff" />
        </div>
      )}

      {weather.main && !error && <WeatherView weatherData={weather} />}
    </div>
  );
}
