import Head from 'next/head';
import { useState, useEffect } from 'react';
import WeatherView from 'components/WeatherView/WeatherView';
import { PulseLoader } from 'react-spinners';
import SearchForm from '../../components/SearchForm';
import Overlay from '../../components/Overlay';
import Background from '../../components/Background';
import fetchWeather from './api/fetchWeather';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!city) {
      return;
    }
    setIsLoading(true);

    fetchWeather(city)
      .then((res) => {
        setWeather(res.data);
      })
      .catch((err) => {
        setError(err);
        toast.error('The city was not found. Please try again');
      })
      .finally(() => {
        setIsLoading(false);
        setError(null);
      });
  }, [city]);

  const onSubmit = (e) => {
    e.preventDefault();
    const searchValue = e.target.elements.searchForm.value;

    if (!searchValue) {
      return toast.warning('Please enter a city name');
    }

    if (searchValue.trim().toLowerCase() === city) return;

    setCity(searchValue.trim().toLowerCase());
    setWeather({});
    e.target.elements.searchForm.value = '';
    // e.target.elements.searchForm.value = '';
  };

  return (
    <div className="h-screen">
      <Head>
        <title>Weather App on NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* app body */}
      <Overlay />

      <Background />

      <SearchForm onSubmitAction={onSubmit} />

      <ToastContainer
        position="top-right"
        autoClose={2000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="dark"
      />

      {/* weather data display */}

      {isLoading && (
        <div className="flex justify-center items-center mt-16">
          <PulseLoader color="#fff" />
        </div>
      )}

      {weather.main && !error && <WeatherView weatherData={weather} />}
    </div>
  );
}
